version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    #ports: #uncomment if not using reverse proxy
    #  - 8000:8000
    #  - 9443:9443
    #  - 9000:9000 # for http
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/stilicho/docker/portainer/data:/data
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.domain.ru`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.domain.ru`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-secure.middlewares=middlewares-authentik@file"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
